version: '3.8'
services:
 postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: docker
     POSTGRES_DB: catalgo-movie
     environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
 
